### ISSUE TITLE
Buglet: Datenbank-Inkonsistenz durch Dateneingabe 

### ISSUE THREAD

**Issue by jlegen** [jbtronics/Part-DB#11]
Partdb Version vom 25.9.
Beim Hinzufügen eines Bildes zu einem neu erstellten Bauteil ist ein Bild zweimal hinzugefügt worden, was 'bootstrap-typisch' bei Tabletbenutzung häufiger passiert.
Danach einfach eines der Bilder wieder gelöscht - damit war dann allerdings die betreffende Kategorie nicht mehr aufrufbar. 
Fehlermeldung: sinngemäss 'Attachment Nr. n nicht vorhanden' (mit Button zum Neuladen, was hier natürlich nicht hilft).
In der DB war attachement Nr. n tatsächlich 'ordnungsgemäss' gelöscht, das entsprechende Bild mit Nr. n-1 vorhanden. Im Bauteil (parts) allerdings war als master-bild Nr. n eingetragen.
Manuelles Ändern der Tabelle parts auf 'n-1' hat das Problem behoben.
Ich hoffe, das war halbwegs verständlich... :)

**Comment by jbtronics** [comment]
Ok,

war ein Problem in Folge des Benutzersystem, dass der master_picture Wert nicht null werden konnte.
Sollte jetzt gefixt sein.

Wenn du es bestätigen kannst, dann schließe ich diesen Issue.

**Comment by jlegen** [comment]
Ja, sieht gut aus, vielen Dank!

**Comment by jbtronics** [comment]
Fixed
