### ISSUE TITLE
Bug: Anzahl vorhandener Bauteile wird auf 0 gesetzt

### ISSUE THREAD

**Issue by jlegen** [jbtronics/Part-DB#12]
Hi,
kleiner Bug - die Anzahl der Bauteile ("Vorhanden") wird "unerwartet" auf 0 gesetzt, wenn
* man ein Bild hinzufügt; das Bauteilformular enthält alle Daten, aber angezeigte Anzahl ist  dann immer "0" - wirkt sich natürlich nur aus, fall man nochmal "Änderungen übernehmen" sagt, was allersdings schonmal vorkommen kann...
* wenn man ein Bauteil in eine andere Kategorie verschiebt, wird der Bestand ebenfalls auf 0 gesetzt - wobei man in diesem Fall den Kategoriewechsel ja immer per "Änderungen übernehmen" speichern muss, sodass die 0 dann gleich mitgespeichert wird...

**Comment by jbtronics** [comment]
Ok, sollte jetzt gefixt sein.
War ein Problem, dass durch das Javascript entstand, dass sich um die Aktivierung/Deaktivierung des Bestandfeldes kümmert, wenn die "Bestand unbekannt" Checkbox geändert wird.

**Comment by jlegen** [comment]
Danke, klappt nun!
