### ISSUE TITLE
Bauteil löschen tut nicht

### ISSUE THREAD

**Issue by jlegen** [jbtronics/Part-DB#15]
Mit der aktuellen Version kann ich offenbar keine Bauteile mehr löschen per "Aktionen", "Bauteil löschen". Es erscheint noch die Sicherheitsabfrage, nach "Ja, löschen" wird aber wieder nur das zu löschende Bauteil angezeigt...

**Comment by jbtronics** [comment]
Sollte jetzt wieder gehen.
