### ISSUE TITLE
Error beim Hinzufügen von Preisen bei einem zweiten Lieferanten

### ISSUE THREAD

**Issue by dkies** [jbtronics/Part-DB#4]
Beim hinzufügen von Preisen bei einem zweiten Lieferanten liefert part-db die Fehlermeldung:
"Die Mengenrabatt-Menge muss bei der ersten Preisangabe "1" sein!"

Nach einem downgrade auf 0.3.1, hinzufügen des ersten Eintrags in die Preisstaffelung und anschließendes
upgrade wieder auf  0.4. können weiter Preise ohne Fehlermeldung hinzugefügt werden.

**Comment by jbtronics** [comment]
Der Fehler sollte nun in der aktuellen Version des nextgen branches behoben sein.
Wenn du den Fix bestätigst hast, dann schließe ich den Issue.

**Comment by dkies** [comment]
Ja, kann ich bestätigen. Die neue Version funktioniert.

**Comment by jbtronics** [comment]
Vielen Dank für deinen Hinweis 👍
